# Jailine Puebla
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jailine Puebla
email: jpueb96@email.unc.edu

#write html inside the double quotes to display in jumbotron
description: "<h3>Hello, world!</h3><h1>#COLLEGE</h1><h3>I'm Still Figuring it Out</h3>Hope you like it!"



baseurl:
url: "/"
github_username:  jpueb96

# Build settings
markdown: kramdown
